name: Process GitHub Issues

on:
  issues:
    types: [opened]

jobs:
  process_issue:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Process issue data
        run: |
          echo "Processing new issue..."
          
          # Issue 내용 추출 (User ID와 댓글을 파싱)
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          
          # 예시: Issue에 포함된 데이터를 처리 (로그로 출력)
          echo "Issue Title: $ISSUE_TITLE"
          echo "Issue Body: $ISSUE_BODY"
          
          # 필요한 처리를 추가 (예: 데이터베이스에 저장, 다른 API 호출 등)
